// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	golibqdconfig "github.com/sylr/go-libqd/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cerberus) DeepCopyInto(out *Cerberus) {
	*out = *in
	if in.Verbose != nil {
		in, out := &in.Verbose, &out.Verbose
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	out.Slack = in.Slack
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cerberus.
func (in *Cerberus) DeepCopy() *Cerberus {
	if in == nil {
		return nil
	}
	out := new(Cerberus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyConfig is an autogenerated deepcopy function, copying the receiver, creating a new golibqdconfig.Config.
func (in *Cerberus) DeepCopyConfig() golibqdconfig.Config {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
